# Generated by Django 3.2.4 on 2021-06-17 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField(max_length=300)),
                ('location', models.CharField(max_length=50)),
                ('img_urls', models.CharField(max_length=150)),
                ('highlights', models.TextField(max_length=200)),
                ('fun_fact', models.TextField(max_length=150)),
                ('website', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField(max_length=300)),
                ('location', models.CharField(max_length=50)),
                ('img_urls', models.CharField(max_length=150)),
                ('highlights', models.TextField(max_length=200)),
                ('fun_fact', models.TextField(max_length=150)),
                ('website', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
