# Generated by Django 3.2.4 on 2021-06-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_artist_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='img_urls',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='img_urls',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='website',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
