# Generated by Django 3.2.4 on 2021-06-21 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210620_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='img_urls',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='img_urls',
        ),
        migrations.AddField(
            model_name='artist',
            name='profile_img',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='gallery',
            name='profile_img',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Gallery_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Artist_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.artist')),
            ],
        ),
    ]
