# Generated by Django 3.2.4 on 2021-06-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210621_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='artists',
            field=models.ManyToManyField(blank=True, to='main_app.Artist'),
        ),
    ]
