# Generated by Django 3.2.4 on 2021-06-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_gallery_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='artists',
        ),
        migrations.AddField(
            model_name='artist',
            name='galleries',
            field=models.ManyToManyField(blank=True, to='main_app.Gallery'),
        ),
    ]
