# Generated by Django 3.2.4 on 2021-06-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210622_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='blurb',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gallery',
            name='blurb',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
