# Generated by Django 3.2.4 on 2021-06-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210623_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='artists',
            field=models.ManyToManyField(blank=True, to='main_app.Artist'),
        ),
    ]
